import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, ArrowRight, Check, ChevronDown, Copy, Download, LoaderCircle, Play, Square, Terminal, Wallet, Sparkles, Braces, LockKeyhole, Search, X } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import './playground.css';

type Status = { ready: boolean; enabled: boolean; busy: boolean; message: string; model: string; runsRemaining: number; priceTinybars: string; maxSteps: number; wallet: { address?: string; accountId?: string; ready: boolean; balanceTinybars?: string; message: string; explorerUrl?: string; faucetUrl?: string } };
type Event = { type: string; at: string; name?: string; callId?: string; args?: unknown; result?: any; message?: string; text?: string; tools?: string[]; locked?: boolean; requirements?: { amount: string; payTo: string; network: string }; settlement?: { transaction?: string; network?: string }; status?: string; grounded?: boolean; paid?: boolean; querySucceeded?: boolean; durationMs?: number; step?: number; [key: string]: unknown };
const examples = ['Show the 5 latest Uniswap V3 swaps on Ethereum with amounts and token symbols.', 'Find active Aave subgraphs on Ethereum and query a small sample of lending data.', 'Show the 5 largest recent Uniswap V3 pools on Ethereum by TVL in USD.'];
function formatHbar(tiny?: string) { if (!tiny) return '—'; const n = BigInt(tiny); return `${n / 100000000n}.${(n % 100000000n).toString().padStart(8, '0')}`.replace(/\.?0+$/, ''); }
function label(event: Event) {
  if (event.type === 'tool_call') return event.name;
  if (event.type === 'tool_result') return `${event.name} · ${event.isError ? 'error' : 'response'}`;
  return ({ run_started: 'MCP session connected', tools_changed: event.locked ? 'Toolkit locked' : 'Real tools enabled', agent_working: `Gemini · step ${event.step}`, payment_quote: 'x402 quote received', wallet_signed: 'Shared wallet signed', payment_settled: 'Payment settled on Hedera', answer: 'Agent answer', error: 'Run needs attention', done: `Run ${event.status}` } as Record<string,string>)[event.type] ?? event.type;
}
function eventCategory(e: Event) { return e.type.startsWith('payment') || e.type === 'wallet_signed' ? 'Payments' : e.type === 'tool_result' ? 'Data' : e.type === 'tool_call' || e.type === 'tools_changed' ? 'Tools' : 'Agent'; }
export default function Playground() {
  const [status, setStatus] = useState<Status>();
  const [prompt, setPrompt] = useState(examples[0]);
  const [events, setEvents] = useState<Event[]>([]);
  const [running, setRunning] = useState(false);
  const [filter, setFilter] = useState('All');
  const [outputTab, setOutputTab] = useState('Answer');
  const [elapsed, setElapsed] = useState(0);
  const [autoScroll, setAutoScroll] = useState(true);
  const [copy, setCopy] = useState(false);
  const controller = useRef<AbortController | null>(null);
  const consoleEnd = useRef<HTMLDivElement>(null);
  const refresh = async () => { try { const r = await fetch('/api/playground/status'); if (!r.ok) throw new Error(); setStatus(await r.json()); } catch { setStatus(s => s ? { ...s, ready: false, message: 'Status connection interrupted. Retrying…' } : undefined); } };
  useEffect(() => { void refresh(); const timer = setInterval(refresh, 15000); return () => { clearInterval(timer); controller.current?.abort(); }; }, []);
  useEffect(() => { if (!running) return; const start = Date.now(); const t = setInterval(() => setElapsed(Math.floor((Date.now() - start) / 1000)), 1000); return () => clearInterval(t); }, [running]);
  useEffect(() => { if (autoScroll && running) consoleEnd.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }, [events, autoScroll, running]);
  const answer = events.findLast(e => e.type === 'answer');
  const lastError = events.findLast(e => e.type === 'error');
  const settled = events.find(e => e.type === 'payment_settled');
  const unlocked = events.find(e => e.type === 'tools_changed' && !e.locked);
  const done = events.findLast(e => e.type === 'done');
  const toolCalls = events.filter(e => e.type === 'tool_call');
  const queryResults = events.filter(e => e.type === 'tool_result' && e.name?.startsWith('execute_query_'));
  const current = events.findLast(e => ['tool_call', 'payment_quote', 'wallet_signed', 'payment_settled', 'agent_working', 'error', 'done'].includes(e.type));
  const phase = !events.length ? -1 : answer ? 5 : queryResults.length || toolCalls.some(e=>e.name?.startsWith('execute_query_')) ? 4 : toolCalls.some(e=>e.name?.startsWith('get_schema_')) ? 3 : unlocked ? 2 : events.some(e=>e.type === 'payment_quote') ? 1 : 0;
  const download = () => { const blob = new Blob([JSON.stringify({ prompt, events }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'intentgraph-run.json'; a.click(); URL.revokeObjectURL(url); };
  async function run() {
    if (running || !prompt.trim() || !status?.ready) return;
    setEvents([]); setElapsed(0); setRunning(true); setOutputTab('Answer');
    const ctrl = new AbortController(); controller.current = ctrl;
    let completed = false;
    try {
      const response = await fetch('/api/playground/run', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt: prompt.trim() }), signal: ctrl.signal });
      if (!response.ok || !response.body) throw new Error(response.status === 429 ? 'Demo rate limit reached. Please wait before trying again.' : 'Unable to start the run. Refresh the playground status.');
      const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = '';
      const consume = (line: string) => { if (!line.trim()) return; const event = JSON.parse(line) as Event; if (event.type === 'heartbeat') return; if (event.type === 'done') completed = true; setEvents(all => [...all, event]); };
      while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); let newline: number; while ((newline = buffer.indexOf('\n')) >= 0) { consume(buffer.slice(0,newline)); buffer = buffer.slice(newline + 1); } }
      buffer += decoder.decode(); if (buffer.trim()) consume(buffer);
      if (!completed) throw new Error('The stream ended before completion. Check the console and wallet before retrying.');
    } catch (error) {
      setEvents(all => [...all, { type: 'error', at: new Date().toISOString(), message: ctrl.signal.aborted ? 'Stopped viewing this run. A payment already submitted may still settle; the shared wallet finishes safely on the server.' : error instanceof Error ? error.message : 'The run failed.' }]);
    } finally { setRunning(false); controller.current = null; void refresh(); }
  }
  return <div className="playground-shell">
    <header className="pg-header"><a href="/" className="pg-brand"><span>⌘</span> IntentGraph <small>PLAYGROUND</small></a><a href="/" className="pg-back"><ArrowLeft size={14}/> Back to the protocol</a><span className="pg-testnet"><i/>HEDERA TESTNET</span></header>
    <main className="pg-main"><div className="pg-title-row"><div><div className="eyebrow">INTENT IN. WATCH IT HAPPEN.</div><h1>A front-row seat<br className="pg-mobile"/> to <em>agentic data.</em></h1><p>Give Gemini a question. Watch it pay, discover, and query through the real MCP.</p></div><div className="pg-model"><Sparkles size={17}/><span>YOUR DEMO AGENT<strong>{status?.model ?? 'Connecting…'}</strong></span></div></div>
      <div className="pg-wallet-strip"><div><Wallet size={20}/><span>SHARED DEMO WALLET<strong>{status?.wallet.accountId ?? (status?.wallet.address ? `${status.wallet.address.slice(0,8)}…${status.wallet.address.slice(-6)}` : 'Checking wallet…')}</strong></span></div><div><span>TESTNET BALANCE<strong>{formatHbar(status?.wallet.balanceTinybars)} <small>HBAR</small></strong></span></div><div><span>PER DEMO RUN<strong>{formatHbar(status?.priceTinybars)} <small>HBAR</small></strong></span></div><div><span>TODAY’S DEMO BUDGET<strong>{status?.runsRemaining ?? '—'} <small>runs left</small></strong></span></div>{status?.wallet.explorerUrl && <a href={status.wallet.explorerUrl} target="_blank" rel="noreferrer">View wallet <ArrowUpRight size={14}/></a>}</div>
      {!status?.ready && !running && <div className="pg-notice" role="status">{status?.message ?? 'Checking Gemini and the shared wallet…'}<button onClick={()=>void refresh()}>Refresh status</button></div>}
      <div className="pg-workspace"><section className="pg-request"><div className="pg-card-heading"><span className="mono">01 / YOUR INTENT</span><Sparkles size={16}/></div><label htmlFor="intent">What would you like to know?</label><textarea id="intent" value={prompt} onChange={e=>setPrompt(e.target.value)} maxLength={1500} disabled={running} placeholder="Show me the latest Uniswap swaps on Ethereum…" onKeyDown={e=>{if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') void run();}}/><div className="pg-input-foot"><span>{prompt.length} / 1500</span><span>Ctrl / ⌘ + Enter to run</span></div><div className="pg-examples"><span>OR TRY A STARTING POINT</span>{['Latest Uniswap swaps', 'Explore Aave lending', 'Largest Uniswap pools'].map((text,i)=><button disabled={running} key={text} onClick={()=>setPrompt(examples[i])}>{text}<ArrowUpRight size={13}/></button>)}</div><button className="pg-run" disabled={!running && (!status?.ready || prompt.trim().length < 8)} onClick={()=>running ? controller.current?.abort() : void run()}>{running ? <><Square size={14}/> Stop run <span>{elapsed}s</span></> : <><Play size={15}/> Run the real flow <ArrowRight size={17}/></>}</button><p className="pg-disclosure">We cover this demo using a shared testnet wallet. Your prompt and tool results are sent to Gemini. No wallet or API key is needed from visitors.</p><div className="pg-session"><LockKeyhole size={14}/><span>Shared funds. Separate MCP sessions.<br/>One payment per run. Keys stay on the server.</span></div></section>
        <section className="pg-execution"><div className="pg-card-heading"><span className="mono">02 / LIVE EXECUTION</span><span className={`pg-run-status ${running ? 'is-running' : ''}`}>{running && <LoaderCircle size={13} className="spin"/>}{running ? 'RUNNING' : done ? String(done.status).toUpperCase() : events.length ? 'STOPPED' : 'READY WHEN YOU ARE'}</span></div><div className="pg-pipeline">{[{ text: 'Connect', icon: Terminal },{ text: 'Pay', icon: Wallet },{ text: 'Discover', icon: Search },{ text: 'Schema', icon: Braces },{ text: 'Query', icon: ArrowUpRight },{ text: 'Answer', icon: Sparkles }].map((s,i)=><div key={s.text} className={`${phase > i ? 'complete' : ''} ${phase === i ? 'active' : ''}`}><span>{phase > i ? <Check size={17}/> : <s.icon size={17}/>}</span><small>{s.text}</small></div>)}</div><div className="pg-live-line"><span className={running ? 'pulse-dot' : ''}/>{current ? label(current) : 'Your agent’s next move will appear here.'}</div><div className="pg-console"><div className="pg-console-bar"><span><Terminal size={14}/> Agent console</span><div><label><input type="checkbox" checked={autoScroll} onChange={e=>setAutoScroll(e.target.checked)}/> Follow</label><button disabled={!events.length} onClick={download} aria-label="Download run trace"><Download size={14}/></button></div></div><div className="pg-console-filters">{['All','Tools','Payments','Data'].map(f=><button key={f} aria-pressed={filter === f} onClick={()=>setFilter(f)}>{f}{f === 'All' && <span>{events.length}</span>}</button>)}</div><div className="pg-console-body" role="log" aria-label="Agent tool calls and data"><div className="pg-console-intro"><span>intentgraph / live-session</span><p>Every entry below comes from this run.<br/>No staged calls. No simulated payments.</p></div>{events.filter(e=>filter === 'All' || eventCategory(e) === filter).map((event,i)=><details key={`${event.at}-${i}`} className={`pg-event ${event.type === 'error' || event.isError ? 'error' : ''} ${event.type === 'payment_settled' ? 'settled' : ''}`}><summary><time>{new Date(event.at).toLocaleTimeString('en-GB',{hour12:false})}</time><span className="pg-event-tag">{eventCategory(event)}</span><strong>{label(event)}</strong><ChevronDown size={12}/></summary>{event.message && <p>{event.message}</p>}<pre>{JSON.stringify(event.result ?? event.args ?? event.requirements ?? event.settlement ?? { ...event, at: undefined, type: undefined, runId: undefined }, null, 2)}</pre></details>)}<div ref={consoleEnd}/></div></div></section></div>
      <section className="pg-output"><div className="pg-output-heading"><div><span className="mono">03 / THE RESULT</span><h2>{answer ? 'From your question to <em>an answer.</em>' : 'The data behind the answer.'}</h2></div><div className="pg-output-tabs">{['Answer','Raw data'].map(t=><button key={t} aria-pressed={outputTab === t} onClick={()=>setOutputTab(t)}>{t}</button>)}</div></div>{settled && <div className="pg-receipt"><Check size={15}/><span>Payment settled</span><code>{settled.settlement?.transaction}</code>{settled.settlement?.transaction && <a href={`https://hashscan.io/testnet/transaction/${encodeURIComponent(settled.settlement.transaction)}`} target="_blank" rel="noreferrer">View receipt <ArrowUpRight size={13}/></a>}</div>}{outputTab === 'Answer' ? answer ? <div className="pg-answer"><div className="pg-answer-meta"><span><Sparkles size={14}/>{answer.grounded ? 'Answer based on returned query data' : 'Agent response · no successful query yet'}</span><button onClick={async()=>{try { await navigator.clipboard.writeText(answer.text ?? ''); setCopy(true); setTimeout(()=>setCopy(false),2000); } catch {setCopy(false);} }}>{copy ? <Check size={14}/> : <Copy size={14}/>} {copy ? 'Copied' : 'Copy answer'}</button></div><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ img: () => null, a: ({ children, href }) => <a href={href} target="_blank" rel="noreferrer">{children}</a> }}>{answer.text ?? ''}</ReactMarkdown></div> : <div className="pg-result-empty">{running ? <LoaderCircle className="spin" size={25}/> : lastError ? <X size={25}/> : <Braces size={25}/>}<h3>{running ? 'Following the evidence…' : lastError ? 'This run could not finish.' : 'An answer, backed by actual calls.'}</h3><p>{running ? 'The console is live. Your answer will appear when Gemini finishes.' : lastError ? lastError.message : 'Start a run to see Gemini’s answer alongside the raw subgraph response.'}</p></div> : <div className="pg-raw">{queryResults.length ? queryResults.map((q,i)=><details open key={i}><summary>{q.name} · response {i+1}</summary><pre>{JSON.stringify(q.result, null, 2)}</pre></details>) : <p>No GraphQL query response has been received in this run.</p>}</div>}</section>
      <footer className="pg-footer"><span>Gemini reasons. The Graph answers. Hedera settles.</span><a href="/#developers">Use your own agent <ArrowUpRight size={14}/></a></footer>
    </main>
  </div>;
}
